apiVersion: apps/v1
kind: Deployment
metadata:
  name: userprofileapi
  labels:
    app: userprofileapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userprofileapi
  template:
    metadata:
      labels:
        app: userprofileapi
    spec:
      containers:
        - name: userprofileapi
          image: hacker3.azurecr.io/userprofileapi:v1
          ports:
            - containerPort: 80
          env:
            - name: PORT
              value: "80"
            - name: CONFIG_FILES_PATH
              value: "/secrets"
            - name: SQL_USER
              value: "sqladminvOx1488"
            - name: SQL_PASSWORD
              value: "nH9fl8Tp7"
            - name: SQL_SERVER
              value: "sqlservervox1488.database.windows.net"
            - name: SQL_DBNAME
              value: "mydrivingDB"
---
apiVersion: v1
kind: Service
metadata:
  name: userprofileapi
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
  selector:
    app: userprofileapi