apiVersion: apps/v1
kind: Deployment
metadata:
  name: poi
  labels:
    app: poi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poi
  template:
    metadata:
      labels:
        app: poi
    spec:
      containers:
        - name: poi
          image: hacker3.azurecr.io/tripinsights/poi:1.0
          ports:
            - containerPort: 80
          env:
            - name: WEB_PORT
              value: "80"
            - name: CONFIG_FILES_PATH
              value: "/secrets"
            - name: SQL_USER
              value: "sqladminvOx1488"
            - name: SQL_PASSWORD
              value: "nH9fl8Tp7"
            - name: SQL_SERVER
              value: "sqlservervox1488.database.windows.net"
            - name: SQL_DBNAME
              value: "mydrivingDB"
            - name: WEB_SERVER_BASE_URI
              value: "http://poi"
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
---
apiVersion: v1
kind: Service
metadata:
  name: poi
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
  selector:
    app: poi