apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-java
  namespace: tripapi
  labels:
    app: userprofile
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userprofile
  template:
    metadata:
      labels:
        app: userprofile
    spec:
      containers:
        - name: userprofile
          image: hacker3.azurecr.io/userprofileapi:v1
          volumeMounts:
            - name: kvvolume
              mountPath: /secrets
              readOnly: true
          ports:
            - containerPort: 80
          env:
            - name: PORT
              value: "80"
            - name: CONFIG_FILES_PATH
              value: "/secrets"
            - name: SQL_USER
              value: "sqladminvOx1488"
            - name: SQL_SERVER
              value: "sqlservervox1488.database.windows.net"
            - name: SQL_DBNAME
              value: "mydrivingDB"
      volumes:
        - name: kvvolume
          flexVolume:
            driver: "azure/kv"
            secretRef:
              name: kvcreds                                                          
            options:
              keyvaultname: "hackteam1kv"                                            # [REQUIRED] the name of the KeyVault
              keyvaultobjectnames: "SQL-PASSWORD"                                    # [REQUIRED] list of KeyVault object names (semi-colon separated)
              keyvaultobjectaliases: "SQL_PASSWORD"                                  # [OPTIONAL] list of KeyVault object aliases
              keyvaultobjecttypes: secret                                            # [REQUIRED] list of KeyVault object types: secret, key,cert (semi-colon separated)
              resourcegroup: "teamResources"                                         # [REQUIRED for version < v0.0.14] the resource group ofthe KeyVault
              subscriptionid: "37d34961-9643-4b36-bb4d-d6490a5e747b"                 # [REQUIRED for version < v0.0.14] the subscription ID of the KeyVault
              tenantid: "cbddfaac-0fb1-417c-aac3-8d2fa625eb0b"                       # [REQUIRED] the tenant ID of the KeyVault
---
apiVersion: v1
kind: Service
metadata:
  name: userprofile
  namespace: tripapi
spec:
  type: ClusterIP
  ports:
    - name: 
      port: 80
  selector:
    app: userprofile