apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-web
  namespace: tripviewer
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: tripviewer
          servicePort: 80
        path: /